dist: xenial

language: go

env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

go:
  - 1.11.x

git:
  depth: 1

install: true

before_script:
  - make setup
  - make copy-config

script:
  - make test
  - make build
