dist: xenial

language: go

go:
  - 1.11.x

git:
  depth: 1

install: true

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/mattn/goveralls

script:
  - make test-ci
