dist: xenial

language: go

env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

go:
  - 1.11.x

git:
  depth: 1

install: true

before_script:
  - go install github.com/golang/dep/cmd/dep
  - go install github.com/golang/lint/golint

script:
  - make test-ci
