dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install: true

before_script:
  - go install github.com/golang/dep/cmd/dep
  - go install github.com/golang/lint/golint
  - go install github.com/axw/gocov/gocov

script:
  - make test-ci
